### ISSUE TITLE
Unable to install gem chef-provisoning-google

### ISSUE THREAD

**Issue by phanikumar1210** [chef/chef-provisioning-google#13]
Hello team,
I am trying to install chef-provisioning-google gem and getting an error specifying that there is no gem. I tried to install it from the git source directly but it is getting failed. Can anyone help me on this.

**Comment by tas50** [comment]
We don't currently have a gem pushed to Rubygems. Now that the refactoring PRs have been merged I'm planning to push the 0.1 version to Rubygems.

**Comment by phanikumar1210** [comment]
Thanks for the response. I was now able to work with chef-provisioning-google by creating a gem of my own and installed it.

**Comment by tas50** [comment]
I pushed the gem today so you can use the official 0.1 release. Thanks for bringing it up. We would have missed it without the nudge.
